# Generated by Django 3.2.5 on 2021-07-18 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('car_id', models.IntegerField()),
                ('customer_need', models.CharField(max_length=10)),
                ('car_title', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('message', models.TextField(blank=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 21, 56, 1, 212035))),
            ],
        ),
    ]
